//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""3e3fb338-738f-402b-b6e9-a52b75723003"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""d48f337f-4064-4538-a72d-f55ed24fda0f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jab"",
                    ""type"": ""Button"",
                    ""id"": ""2e4f861d-9a3c-4f0c-b3c6-a2e2ab0f396f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right_Hook"",
                    ""type"": ""Button"",
                    ""id"": ""c3a507cd-1867-4c8d-97ed-f63e5a4a25ca"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Uppercut"",
                    ""type"": ""Button"",
                    ""id"": ""758e972a-5db8-45bc-9516-3f2fe59420a1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Perryjab"",
                    ""type"": ""Button"",
                    ""id"": ""ab135267-bf9e-4ccb-a5b1-f4dcf9c0d2f6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""perry hook"",
                    ""type"": ""Button"",
                    ""id"": ""f9839cb3-5bef-4d53-ba61-e032df384cd0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""perry uppercut"",
                    ""type"": ""Button"",
                    ""id"": ""3c4b9ab0-04a1-4484-815f-12698029a64d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""doge"",
                    ""type"": ""Button"",
                    ""id"": ""7ad430b6-176f-4067-ab8c-1ef201c94856"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""block"",
                    ""type"": ""Button"",
                    ""id"": ""5e06d3b7-f67e-45c9-98e9-b3fdefb3cb38"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""legwork"",
                    ""type"": ""Button"",
                    ""id"": ""e4514c42-e093-40e4-bc21-1333461239c1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1st Player"",
                    ""id"": ""cae97f5c-12f1-4d79-81ca-2973584058e6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""948187d2-4fcf-4316-89f6-c3bde5997aa6"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""29735abb-673c-469c-9bdb-8f227e30b798"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""459bf4b2-7a42-4a3a-9cd4-4d0fedd3cf06"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8146534b-0bf0-4a82-b283-ff32e738be5c"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e726deed-dd0b-421b-a44d-ed60973f8ce2"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b04cf8a8-de21-40f6-bb62-ff0a08e791f9"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Uppercut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b8710b6-8835-4d8e-afdb-7f219f3cd31a"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Uppercut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3fb83d93-8cda-476c-99b2-8b2dd67f3fac"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right_Hook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f494108-06be-4614-9ea5-80a26d6322cd"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right_Hook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ace2fe2c-0fcf-4cd9-a854-27c22ec5f18e"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69f4338b-73ec-4418-ae3d-b4b7b8e88be1"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b3b3e7f-f889-4fd1-8e54-dd559e8f43ee"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Perryjab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1"",
                    ""id"": ""ed5dd7c0-84e4-472d-9e31-c30e191016e9"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Perryjab"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""e1ae5b29-5724-4d78-9590-a1888377b950"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Perryjab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""7021e241-8f16-44af-b9ae-2954c12761b5"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Perryjab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b6e8fe86-ba22-4229-b89a-09a9bd76c095"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""perry uppercut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1"",
                    ""id"": ""3ddba309-3a5a-4e9d-ade1-15f205f67910"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""perry uppercut"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""ad538799-b129-4a76-b440-422ca1a224e0"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""perry uppercut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""0aa99e5d-f36d-4c3a-9315-ab1166715344"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""perry uppercut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""7924d341-3510-4f3c-9099-f0529f1cf190"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""perry hook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1"",
                    ""id"": ""dfc395f0-9b12-43a5-a2c9-0e0e5b7322ea"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""perry hook"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""7a5e628e-6cc4-434f-b345-0d5c883dd99c"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""perry hook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""b5300dee-7bcc-491c-a8a3-15fad5f0eaa3"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""perry hook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4fc2895b-d645-4c9b-9066-703517a20648"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""doge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""979d5e93-6333-4d3c-be8c-ee0eadfbc1af"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""doge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42cdf70e-4dfb-4890-a642-df9db38c7769"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a8daa37-0222-43a1-9bd4-92fa808964ee"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""115bedd0-cec9-49f0-9663-283ae9ef2da3"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""legwork"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""269ed1ef-9ee0-4f11-9486-1b69da4f55c1"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""legwork"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""tutorial"",
            ""id"": ""63c34ae8-090a-40b9-8b4e-2e42e5f5e1cb"",
            ""actions"": [
                {
                    ""name"": ""next line"",
                    ""type"": ""Button"",
                    ""id"": ""a1299cfb-898a-42b5-ad77-da0d9a84208b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""25828a4a-c724-48c2-aae8-6b031d93aebf"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""next line"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a21b922a-b415-4333-803d-641d124d4027"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""next line"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69141ca8-4c80-47f9-9bea-5786a438e44d"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""next line"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""cd6b9758-e506-467d-a36c-fc81b43783c0"",
            ""actions"": [
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""c981df20-0f9a-4e7b-aa17-90c84e535121"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c4f2408a-237d-4ede-ad7f-2414dba0070a"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f606d049-4021-4b24-84d6-f04ebbf93f7a"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_Move = m_Gameplay.FindAction("Move", throwIfNotFound: true);
        m_Gameplay_Jab = m_Gameplay.FindAction("Jab", throwIfNotFound: true);
        m_Gameplay_Right_Hook = m_Gameplay.FindAction("Right_Hook", throwIfNotFound: true);
        m_Gameplay_Uppercut = m_Gameplay.FindAction("Uppercut", throwIfNotFound: true);
        m_Gameplay_Perryjab = m_Gameplay.FindAction("Perryjab", throwIfNotFound: true);
        m_Gameplay_perryhook = m_Gameplay.FindAction("perry hook", throwIfNotFound: true);
        m_Gameplay_perryuppercut = m_Gameplay.FindAction("perry uppercut", throwIfNotFound: true);
        m_Gameplay_doge = m_Gameplay.FindAction("doge", throwIfNotFound: true);
        m_Gameplay_block = m_Gameplay.FindAction("block", throwIfNotFound: true);
        m_Gameplay_legwork = m_Gameplay.FindAction("legwork", throwIfNotFound: true);
        // tutorial
        m_tutorial = asset.FindActionMap("tutorial", throwIfNotFound: true);
        m_tutorial_nextline = m_tutorial.FindAction("next line", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Pause = m_UI.FindAction("Pause", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_Move;
    private readonly InputAction m_Gameplay_Jab;
    private readonly InputAction m_Gameplay_Right_Hook;
    private readonly InputAction m_Gameplay_Uppercut;
    private readonly InputAction m_Gameplay_Perryjab;
    private readonly InputAction m_Gameplay_perryhook;
    private readonly InputAction m_Gameplay_perryuppercut;
    private readonly InputAction m_Gameplay_doge;
    private readonly InputAction m_Gameplay_block;
    private readonly InputAction m_Gameplay_legwork;
    public struct GameplayActions
    {
        private @PlayerInputActions m_Wrapper;
        public GameplayActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Gameplay_Move;
        public InputAction @Jab => m_Wrapper.m_Gameplay_Jab;
        public InputAction @Right_Hook => m_Wrapper.m_Gameplay_Right_Hook;
        public InputAction @Uppercut => m_Wrapper.m_Gameplay_Uppercut;
        public InputAction @Perryjab => m_Wrapper.m_Gameplay_Perryjab;
        public InputAction @perryhook => m_Wrapper.m_Gameplay_perryhook;
        public InputAction @perryuppercut => m_Wrapper.m_Gameplay_perryuppercut;
        public InputAction @doge => m_Wrapper.m_Gameplay_doge;
        public InputAction @block => m_Wrapper.m_Gameplay_block;
        public InputAction @legwork => m_Wrapper.m_Gameplay_legwork;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Jab.started += instance.OnJab;
            @Jab.performed += instance.OnJab;
            @Jab.canceled += instance.OnJab;
            @Right_Hook.started += instance.OnRight_Hook;
            @Right_Hook.performed += instance.OnRight_Hook;
            @Right_Hook.canceled += instance.OnRight_Hook;
            @Uppercut.started += instance.OnUppercut;
            @Uppercut.performed += instance.OnUppercut;
            @Uppercut.canceled += instance.OnUppercut;
            @Perryjab.started += instance.OnPerryjab;
            @Perryjab.performed += instance.OnPerryjab;
            @Perryjab.canceled += instance.OnPerryjab;
            @perryhook.started += instance.OnPerryhook;
            @perryhook.performed += instance.OnPerryhook;
            @perryhook.canceled += instance.OnPerryhook;
            @perryuppercut.started += instance.OnPerryuppercut;
            @perryuppercut.performed += instance.OnPerryuppercut;
            @perryuppercut.canceled += instance.OnPerryuppercut;
            @doge.started += instance.OnDoge;
            @doge.performed += instance.OnDoge;
            @doge.canceled += instance.OnDoge;
            @block.started += instance.OnBlock;
            @block.performed += instance.OnBlock;
            @block.canceled += instance.OnBlock;
            @legwork.started += instance.OnLegwork;
            @legwork.performed += instance.OnLegwork;
            @legwork.canceled += instance.OnLegwork;
        }

        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Jab.started -= instance.OnJab;
            @Jab.performed -= instance.OnJab;
            @Jab.canceled -= instance.OnJab;
            @Right_Hook.started -= instance.OnRight_Hook;
            @Right_Hook.performed -= instance.OnRight_Hook;
            @Right_Hook.canceled -= instance.OnRight_Hook;
            @Uppercut.started -= instance.OnUppercut;
            @Uppercut.performed -= instance.OnUppercut;
            @Uppercut.canceled -= instance.OnUppercut;
            @Perryjab.started -= instance.OnPerryjab;
            @Perryjab.performed -= instance.OnPerryjab;
            @Perryjab.canceled -= instance.OnPerryjab;
            @perryhook.started -= instance.OnPerryhook;
            @perryhook.performed -= instance.OnPerryhook;
            @perryhook.canceled -= instance.OnPerryhook;
            @perryuppercut.started -= instance.OnPerryuppercut;
            @perryuppercut.performed -= instance.OnPerryuppercut;
            @perryuppercut.canceled -= instance.OnPerryuppercut;
            @doge.started -= instance.OnDoge;
            @doge.performed -= instance.OnDoge;
            @doge.canceled -= instance.OnDoge;
            @block.started -= instance.OnBlock;
            @block.performed -= instance.OnBlock;
            @block.canceled -= instance.OnBlock;
            @legwork.started -= instance.OnLegwork;
            @legwork.performed -= instance.OnLegwork;
            @legwork.canceled -= instance.OnLegwork;
        }

        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);

    // tutorial
    private readonly InputActionMap m_tutorial;
    private List<ITutorialActions> m_TutorialActionsCallbackInterfaces = new List<ITutorialActions>();
    private readonly InputAction m_tutorial_nextline;
    public struct TutorialActions
    {
        private @PlayerInputActions m_Wrapper;
        public TutorialActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @nextline => m_Wrapper.m_tutorial_nextline;
        public InputActionMap Get() { return m_Wrapper.m_tutorial; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TutorialActions set) { return set.Get(); }
        public void AddCallbacks(ITutorialActions instance)
        {
            if (instance == null || m_Wrapper.m_TutorialActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TutorialActionsCallbackInterfaces.Add(instance);
            @nextline.started += instance.OnNextline;
            @nextline.performed += instance.OnNextline;
            @nextline.canceled += instance.OnNextline;
        }

        private void UnregisterCallbacks(ITutorialActions instance)
        {
            @nextline.started -= instance.OnNextline;
            @nextline.performed -= instance.OnNextline;
            @nextline.canceled -= instance.OnNextline;
        }

        public void RemoveCallbacks(ITutorialActions instance)
        {
            if (m_Wrapper.m_TutorialActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITutorialActions instance)
        {
            foreach (var item in m_Wrapper.m_TutorialActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TutorialActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TutorialActions @tutorial => new TutorialActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    private readonly InputAction m_UI_Pause;
    public struct UIActions
    {
        private @PlayerInputActions m_Wrapper;
        public UIActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pause => m_Wrapper.m_UI_Pause;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
        }

        private void UnregisterCallbacks(IUIActions instance)
        {
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
        }

        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActions @UI => new UIActions(this);
    public interface IGameplayActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJab(InputAction.CallbackContext context);
        void OnRight_Hook(InputAction.CallbackContext context);
        void OnUppercut(InputAction.CallbackContext context);
        void OnPerryjab(InputAction.CallbackContext context);
        void OnPerryhook(InputAction.CallbackContext context);
        void OnPerryuppercut(InputAction.CallbackContext context);
        void OnDoge(InputAction.CallbackContext context);
        void OnBlock(InputAction.CallbackContext context);
        void OnLegwork(InputAction.CallbackContext context);
    }
    public interface ITutorialActions
    {
        void OnNextline(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnPause(InputAction.CallbackContext context);
    }
}
