//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""3e3fb338-738f-402b-b6e9-a52b75723003"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""d48f337f-4064-4538-a72d-f55ed24fda0f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jab"",
                    ""type"": ""Button"",
                    ""id"": ""2e4f861d-9a3c-4f0c-b3c6-a2e2ab0f396f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right_Hook"",
                    ""type"": ""Button"",
                    ""id"": ""c3a507cd-1867-4c8d-97ed-f63e5a4a25ca"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Uppercut"",
                    ""type"": ""Button"",
                    ""id"": ""758e972a-5db8-45bc-9516-3f2fe59420a1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Perryjab"",
                    ""type"": ""Button"",
                    ""id"": ""ab135267-bf9e-4ccb-a5b1-f4dcf9c0d2f6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""perry hook"",
                    ""type"": ""Button"",
                    ""id"": ""f9839cb3-5bef-4d53-ba61-e032df384cd0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""perry uppercut"",
                    ""type"": ""Button"",
                    ""id"": ""3c4b9ab0-04a1-4484-815f-12698029a64d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""doge"",
                    ""type"": ""Button"",
                    ""id"": ""7ad430b6-176f-4067-ab8c-1ef201c94856"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""block"",
                    ""type"": ""Button"",
                    ""id"": ""5e06d3b7-f67e-45c9-98e9-b3fdefb3cb38"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1st Player"",
                    ""id"": ""cae97f5c-12f1-4d79-81ca-2973584058e6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""948187d2-4fcf-4316-89f6-c3bde5997aa6"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""29735abb-673c-469c-9bdb-8f227e30b798"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""459bf4b2-7a42-4a3a-9cd4-4d0fedd3cf06"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8146534b-0bf0-4a82-b283-ff32e738be5c"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e726deed-dd0b-421b-a44d-ed60973f8ce2"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2nd Player"",
                    ""id"": ""2a7fdf41-d58e-44d6-942a-b4ef53043e8b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e1e4c4e3-26cd-4a8f-8a50-76f2e5828421"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""032ed396-17f0-474f-95eb-77832eae63a1"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b04cf8a8-de21-40f6-bb62-ff0a08e791f9"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Uppercut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b8710b6-8835-4d8e-afdb-7f219f3cd31a"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Uppercut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c7f34c1-9589-439c-8816-cdaf1b964401"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Uppercut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3fb83d93-8cda-476c-99b2-8b2dd67f3fac"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right_Hook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f494108-06be-4614-9ea5-80a26d6322cd"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right_Hook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7abf1f9-eb6b-466d-86af-6d34d733e1dd"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right_Hook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ace2fe2c-0fcf-4cd9-a854-27c22ec5f18e"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69f4338b-73ec-4418-ae3d-b4b7b8e88be1"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba6549a7-03b9-44a9-8c40-ee082990e8f6"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b3b3e7f-f889-4fd1-8e54-dd559e8f43ee"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Perryjab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1"",
                    ""id"": ""ed5dd7c0-84e4-472d-9e31-c30e191016e9"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Perryjab"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""e1ae5b29-5724-4d78-9590-a1888377b950"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Perryjab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""7021e241-8f16-44af-b9ae-2954c12761b5"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Perryjab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2"",
                    ""id"": ""f0bf97fc-1417-49ab-b514-d3966fab5259"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Perryjab"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""3c88e9d8-d990-452f-b266-d97f399bd70d"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Perryjab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""63d89984-24c4-4f94-85f1-0805fef05a9c"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Perryjab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b6e8fe86-ba22-4229-b89a-09a9bd76c095"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""perry uppercut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1"",
                    ""id"": ""3ddba309-3a5a-4e9d-ade1-15f205f67910"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""perry uppercut"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""ad538799-b129-4a76-b440-422ca1a224e0"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""perry uppercut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""0aa99e5d-f36d-4c3a-9315-ab1166715344"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""perry uppercut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2"",
                    ""id"": ""63fe01ba-be3b-4b1e-9f75-5af3c77a3113"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""perry uppercut"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""66be5d37-ee00-4b90-aa85-19cb2525fb54"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""perry uppercut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""63d766d4-ab52-4493-a271-bd6c1ffcaaa0"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""perry uppercut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""7924d341-3510-4f3c-9099-f0529f1cf190"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""perry hook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1"",
                    ""id"": ""dfc395f0-9b12-43a5-a2c9-0e0e5b7322ea"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""perry hook"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""7a5e628e-6cc4-434f-b345-0d5c883dd99c"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""perry hook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""b5300dee-7bcc-491c-a8a3-15fad5f0eaa3"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""perry hook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2"",
                    ""id"": ""eb6c2bc6-d322-4f97-9f17-c40593bb91ca"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""perry hook"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""a1540f34-f0d0-41c0-a81c-ffb967a514d1"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""perry hook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""50facb7e-4037-4911-873a-fd6a95fcd8c6"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""perry hook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4fc2895b-d645-4c9b-9066-703517a20648"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""doge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42cdf70e-4dfb-4890-a642-df9db38c7769"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_Move = m_Gameplay.FindAction("Move", throwIfNotFound: true);
        m_Gameplay_Jab = m_Gameplay.FindAction("Jab", throwIfNotFound: true);
        m_Gameplay_Right_Hook = m_Gameplay.FindAction("Right_Hook", throwIfNotFound: true);
        m_Gameplay_Uppercut = m_Gameplay.FindAction("Uppercut", throwIfNotFound: true);
        m_Gameplay_Perryjab = m_Gameplay.FindAction("Perryjab", throwIfNotFound: true);
        m_Gameplay_perryhook = m_Gameplay.FindAction("perry hook", throwIfNotFound: true);
        m_Gameplay_perryuppercut = m_Gameplay.FindAction("perry uppercut", throwIfNotFound: true);
        m_Gameplay_doge = m_Gameplay.FindAction("doge", throwIfNotFound: true);
        m_Gameplay_block = m_Gameplay.FindAction("block", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_Move;
    private readonly InputAction m_Gameplay_Jab;
    private readonly InputAction m_Gameplay_Right_Hook;
    private readonly InputAction m_Gameplay_Uppercut;
    private readonly InputAction m_Gameplay_Perryjab;
    private readonly InputAction m_Gameplay_perryhook;
    private readonly InputAction m_Gameplay_perryuppercut;
    private readonly InputAction m_Gameplay_doge;
    private readonly InputAction m_Gameplay_block;
    public struct GameplayActions
    {
        private @PlayerInputActions m_Wrapper;
        public GameplayActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Gameplay_Move;
        public InputAction @Jab => m_Wrapper.m_Gameplay_Jab;
        public InputAction @Right_Hook => m_Wrapper.m_Gameplay_Right_Hook;
        public InputAction @Uppercut => m_Wrapper.m_Gameplay_Uppercut;
        public InputAction @Perryjab => m_Wrapper.m_Gameplay_Perryjab;
        public InputAction @perryhook => m_Wrapper.m_Gameplay_perryhook;
        public InputAction @perryuppercut => m_Wrapper.m_Gameplay_perryuppercut;
        public InputAction @doge => m_Wrapper.m_Gameplay_doge;
        public InputAction @block => m_Wrapper.m_Gameplay_block;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Jab.started += instance.OnJab;
            @Jab.performed += instance.OnJab;
            @Jab.canceled += instance.OnJab;
            @Right_Hook.started += instance.OnRight_Hook;
            @Right_Hook.performed += instance.OnRight_Hook;
            @Right_Hook.canceled += instance.OnRight_Hook;
            @Uppercut.started += instance.OnUppercut;
            @Uppercut.performed += instance.OnUppercut;
            @Uppercut.canceled += instance.OnUppercut;
            @Perryjab.started += instance.OnPerryjab;
            @Perryjab.performed += instance.OnPerryjab;
            @Perryjab.canceled += instance.OnPerryjab;
            @perryhook.started += instance.OnPerryhook;
            @perryhook.performed += instance.OnPerryhook;
            @perryhook.canceled += instance.OnPerryhook;
            @perryuppercut.started += instance.OnPerryuppercut;
            @perryuppercut.performed += instance.OnPerryuppercut;
            @perryuppercut.canceled += instance.OnPerryuppercut;
            @doge.started += instance.OnDoge;
            @doge.performed += instance.OnDoge;
            @doge.canceled += instance.OnDoge;
            @block.started += instance.OnBlock;
            @block.performed += instance.OnBlock;
            @block.canceled += instance.OnBlock;
        }

        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Jab.started -= instance.OnJab;
            @Jab.performed -= instance.OnJab;
            @Jab.canceled -= instance.OnJab;
            @Right_Hook.started -= instance.OnRight_Hook;
            @Right_Hook.performed -= instance.OnRight_Hook;
            @Right_Hook.canceled -= instance.OnRight_Hook;
            @Uppercut.started -= instance.OnUppercut;
            @Uppercut.performed -= instance.OnUppercut;
            @Uppercut.canceled -= instance.OnUppercut;
            @Perryjab.started -= instance.OnPerryjab;
            @Perryjab.performed -= instance.OnPerryjab;
            @Perryjab.canceled -= instance.OnPerryjab;
            @perryhook.started -= instance.OnPerryhook;
            @perryhook.performed -= instance.OnPerryhook;
            @perryhook.canceled -= instance.OnPerryhook;
            @perryuppercut.started -= instance.OnPerryuppercut;
            @perryuppercut.performed -= instance.OnPerryuppercut;
            @perryuppercut.canceled -= instance.OnPerryuppercut;
            @doge.started -= instance.OnDoge;
            @doge.performed -= instance.OnDoge;
            @doge.canceled -= instance.OnDoge;
            @block.started -= instance.OnBlock;
            @block.performed -= instance.OnBlock;
            @block.canceled -= instance.OnBlock;
        }

        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    public interface IGameplayActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJab(InputAction.CallbackContext context);
        void OnRight_Hook(InputAction.CallbackContext context);
        void OnUppercut(InputAction.CallbackContext context);
        void OnPerryjab(InputAction.CallbackContext context);
        void OnPerryhook(InputAction.CallbackContext context);
        void OnPerryuppercut(InputAction.CallbackContext context);
        void OnDoge(InputAction.CallbackContext context);
        void OnBlock(InputAction.CallbackContext context);
    }
}
